'''Little tool that converts the cube generated by 
http://wiki.alioth.net/index.php/Planettool into individual textures.
Everything is hard coded because it is a little tool.'''

from wand.image import Image

pix = 0
with Image(filename='textures/earth_night.png') as a:
    for i in range(6):
        with a.clone() as img:
            print(pix)
            img.crop(top=pix, height=1024)
            img.save(filename='textures/earth_night_' + str(i) + '.png')
        pix += 1024